In [3]:
import random, numpy as np

tamano_tablero = 10
tablero = np.zeros((tamano_tablero,tamano_tablero), dtype=int)
tablero[0,:] = 9
tablero[9,:] = 9
tablero[:,0] = 9
tablero[:,9] = 9

raton = [5,5]

# --- MOVIMIENTO DEL RATÓN ---
movimientos = [(1,0), (-1,0), (0,1), (0,-1)]  # abajo, arriba, derecha, izquierda
random.shuffle(movimientos)  # mezcla para elegir aleatorio


for dx, dy in movimientos:
    nueva_x = raton[0] + dx
    nueva_y = raton[1] + dy

    print(nueva_x)
    print(nueva_y)

#     # Verifica que no choque contra muros (los 9)
#     if tablero[nueva_x, nueva_y] != 9:
#         raton[0], raton[1] = nueva_x, nueva_y
#         break

6
5
5
4
4
5
5
6


In [4]:
import numpy as np

lista = [(4,4),(5,5), (6,6)]

tablero = np.zeros((10,10), dtype=int)

for ox, oy in lista:
    tablero[ox,oy] = 9

tablero[1,1] = 4

tablero[8,8] = 5

print(tablero)


[[0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 9 0 0 0 0 0]
 [0 0 0 0 0 9 0 0 0 0]
 [0 0 0 0 0 0 9 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [6]:
# Laberinto fijo (10x10)
tablero = [
    [9,9,9,9,9,9,9,9,9,9],
    [9,2,0,0,9,0,0,0,3,9],
    [9,0,9,0,9,0,9,0,0,9],
    [9,0,9,0,0,0,9,9,0,9],
    [9,0,0,0,9,9,0,0,0,9],
    [9,0,9,9,0,0,0,9,0,9],
    [9,0,0,0,0,9,0,0,0,9],
    [9,9,0,9,0,0,0,9,0,9],
    [9,0,0,0,0,9,0,0,0,9],
    [9,9,9,9,9,9,9,9,9,9]
]

for fila in tablero:
    simbolos = []
    for x in fila:
        if x == 9:
            simbolos.append('🧱')
        elif x == 2:
            simbolos.append('🐁')
        elif x == 3:
            simbolos.append('🐈')
        else:
            simbolos.append('🟨')
    print(' '.join(simbolos))

🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱
🧱 🐁 🟨 🟨 🧱 🟨 🟨 🟨 🐈 🧱
🧱 🟨 🧱 🟨 🧱 🟨 🧱 🟨 🟨 🧱
🧱 🟨 🧱 🟨 🟨 🟨 🧱 🧱 🟨 🧱
🧱 🟨 🟨 🟨 🧱 🧱 🟨 🟨 🟨 🧱
🧱 🟨 🧱 🧱 🟨 🟨 🟨 🧱 🟨 🧱
🧱 🟨 🟨 🟨 🟨 🧱 🟨 🟨 🟨 🧱
🧱 🧱 🟨 🧱 🟨 🟨 🟨 🧱 🟨 🧱
🧱 🟨 🟨 🟨 🟨 🧱 🟨 🟨 🟨 🧱
🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱
