In [3]:
import random, numpy as np

tamano_tablero = 10
tablero = np.zeros((tamano_tablero,tamano_tablero), dtype=int)
tablero[0,:] = 9
tablero[9,:] = 9
tablero[:,0] = 9
tablero[:,9] = 9

raton = [5,5]

# --- MOVIMIENTO DEL RATÓN ---
movimientos = [(1,0), (-1,0), (0,1), (0,-1)]  # abajo, arriba, derecha, izquierda
random.shuffle(movimientos)  # mezcla para elegir aleatorio


for dx, dy in movimientos:
    nueva_x = raton[0] + dx
    nueva_y = raton[1] + dy

    print(nueva_x)
    print(nueva_y)

#     # Verifica que no choque contra muros (los 9)
#     if tablero[nueva_x, nueva_y] != 9:
#         raton[0], raton[1] = nueva_x, nueva_y
#         break

6
5
5
4
4
5
5
6


In [4]:
import numpy as np

lista = [(4,4),(5,5), (6,6)]

tablero = np.zeros((10,10), dtype=int)

for ox, oy in lista:
    tablero[ox,oy] = 9

tablero[1,1] = 4

tablero[8,8] = 5

print(tablero)


[[0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 9 0 0 0 0 0]
 [0 0 0 0 0 9 0 0 0 0]
 [0 0 0 0 0 0 9 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [6]:
# Laberinto fijo (10x10)
tablero = [
    [9,9,9,9,9,9,9,9,9,9],
    [9,2,0,0,9,0,0,0,3,9],
    [9,0,9,0,9,0,9,0,0,9],
    [9,0,9,0,0,0,9,9,0,9],
    [9,0,0,0,9,9,0,0,0,9],
    [9,0,9,9,0,0,0,9,0,9],
    [9,0,0,0,0,9,0,0,0,9],
    [9,9,0,9,0,0,0,9,0,9],
    [9,0,0,0,0,9,0,0,0,9],
    [9,9,9,9,9,9,9,9,9,9]
]

for fila in tablero:
    simbolos = []
    for x in fila:
        if x == 9:
            simbolos.append('🧱')
        elif x == 2:
            simbolos.append('🐁')
        elif x == 3:
            simbolos.append('🐈')
        else:
            simbolos.append('🟨')
    print(' '.join(simbolos))

🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱
🧱 🐁 🟨 🟨 🧱 🟨 🟨 🟨 🐈 🧱
🧱 🟨 🧱 🟨 🧱 🟨 🧱 🟨 🟨 🧱
🧱 🟨 🧱 🟨 🟨 🟨 🧱 🧱 🟨 🧱
🧱 🟨 🟨 🟨 🧱 🧱 🟨 🟨 🟨 🧱
🧱 🟨 🧱 🧱 🟨 🟨 🟨 🧱 🟨 🧱
🧱 🟨 🟨 🟨 🟨 🧱 🟨 🟨 🟨 🧱
🧱 🧱 🟨 🧱 🟨 🟨 🟨 🧱 🟨 🧱
🧱 🟨 🟨 🟨 🟨 🧱 🟨 🟨 🟨 🧱
🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱 🧱


KeyboardInterrupt: 

In [ ]:
import numpy as np
import heapq

# ----- CONFIGURACIÓN DEL TABLERO -----
tablero = np.zeros((10,10), dtype=int)
posicion_inicio = (1,1)
posicion_fin = (8,8)

# bordes
tablero[0,:] = 9
tablero[9,:] = 9
tablero[:,0] = 9
tablero[:,9] = 9

# paredes internas
paredes_internas = [
    (4,1), (2,2), (2,4), (2,6), (3,2), (3,6), (3,7),
    (4,4), (4,5), (5,2), (5,3), (5,7), (6,5),
    (7,1), (7,3), (7,7), (8,5)
]
for px, py in paredes_internas:
    tablero[px,py] = 9

# ----- FUNCIONES -----
def movimientos_de_busqueda_posibles(pos_actual):
    movimientos_disponibles = [(1,0),(-1,0),(0,1),(0,-1)]
    movimientos_posibles = []
    for mx, my in movimientos_disponibles:
        posible_x = pos_actual[0] + mx
        posible_y = pos_actual[1] + my
        if tablero[posible_x, posible_y] != 9:
            movimientos_posibles.append((posible_x, posible_y))
    return movimientos_posibles

def distancia_manhattan(p1, p2):
    return abs(p1[0]-p2[0]) + abs(p1[1]-p2[1])




# # # # # # # # # #
# S * *   * * *   #
#   # * # * # * * #
#   # * * * # # * #
# #     # #     * #
#   # #       # * #
#         #     * #
# #   #       # * #
#         #     F #
# # # # # # # # # #


¡Objetivo alcanzado!
Camino final: [(1, 1), (1, 2), (1, 3), (2, 3), (3, 3), (3, 4), (3, 5), (2, 5), (1, 5), (1, 6), (1, 7), (2, 7), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (8, 8)]


In [23]:
import numpy as np
from collections import deque
import time
from IPython.display import clear_output

# ----- CONFIGURACIÓN DEL TABLERO -----
tablero = np.zeros((10,10), dtype=int)
inicio = (1,1)
objetivo = (8,8)

# bordes
tablero[0,:] = 9
tablero[9,:] = 9
tablero[:,0] = 9
tablero[:,9] = 9

# paredes internas
paredes_internas = [(4,1), (2,2), (2,4), (2,6), (3,2), (3,6), (3,7),
                    (4,4), (4,5), (5,2), (5,3), (5,7), (6,5), (7,1),
                    (7,3), (7,7), (8,5)]
for x, y in paredes_internas:
    tablero[x,y] = 9

# ----- FUNCIONES -----
def movimientos_de_busqueda_posibles(pos_actual):
    movimientos_disponibles = [(1,0),(-1,0),(0,1),(0,-1)]
    movimientos_posibles = []
    for mx, my in movimientos_disponibles:
        nx, ny = pos_actual[0] + mx, pos_actual[1] + my
        if tablero[nx, ny] != 9:  # no es pared
            movimientos_posibles.append((nx, ny))
    return movimientos_posibles

def mostrar_tablero(tablero, visitadas, camino_actual):
    """Dibuja el tablero con símbolos"""
    clear_output(wait=True)  # limpia la consola en Jupyter
    simbolos = {0: ' ', 9: '#'}
    for x in range(tablero.shape[0]):
        fila = ''
        for y in range(tablero.shape[1]):
            pos = (x, y)
            if pos == inicio:
                fila += ' S '  # inicio
            elif pos == objetivo:
                fila += ' F '  # fin
            elif pos in camino_actual:
                fila += ' * '  # camino que se sigue
            elif pos in visitadas:
                fila += ' . '  # visitado
            else:
                fila += simbolos.get(tablero[x,y], ' ')
        print(fila)
    time.sleep(0.2)  # pausa para animación

# ----- BFS VISUAL -----
def bfs_visual(inicio, objetivo, tablero):
    cola = deque([(inicio, [inicio])])
    visitadas = {inicio}

    while cola:
        actual, camino = cola.popleft()
        mostrar_tablero(tablero, visitadas, camino)

        if actual == objetivo:
            print("¡Camino más corto encontrado!")
            print("Camino:", camino)
            return camino

        for vecino in movimientos_de_busqueda_posibles(actual):
            if vecino not in visitadas:
                visitadas.add(vecino)
                cola.append((vecino, camino + [vecino]))

    print("No se encontró camino")
    return None

# ----- EJECUCIÓN -----
camino = bfs_visual(inicio, objetivo, tablero)


##########
# S  *  *  *  *  *  *  . #
# . # . # . # *  * #
# . # .  .  . ## * #
## .  . ## .  .  * #
# ##  .  . # * #
#    # .  .  * #
## #   # * #
#    #   F #
##########
¡Camino más corto encontrado!
Camino: [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 7), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (8, 8)]
